name: drone_client
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  get_it: ^8.0.3
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  gamepads: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.3

flutter:
  uses-material-design: true
